name: chat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17 
  sqflite: ^2.0.3
  sqflite_common_ffi: ^2.0.0 
  path: ^1.8.3
  provider: ^6.0.0
  http: ^1.0.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true